name: Algarve-property-rental
favicon: null
layout_spectrum: 0.6688358285464346
typography_spectrum: 0.4825688600540161
title: Your experienced partner
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.990828103851527
  lightness: 0.28259043022990227
  saturation: 0.815191488713026
  rhythmicContrast: 0.9642847431823611
purpose: []
