analytics: {}
color:
  brandColors:
    - '#7c93bc'
    - '#cdbf9c'
    - '#26110c'
    - '#7c7563'
    - '#ece0cf'
  brandStrength: 0.990828
  lightness: 0.502252
  rhythmicContrast: 0.964284
  saturation: 0.515765
cta: {}
layout_spectrum: 0
name: Algarve-property-rental
opengraph: {}
purpose: []
typography_spectrum: 0.653153
